using System.Collections.Generic;
using System.Drawing;
using System.Globalization;

namespace DragNWash.Installer
{
    // The installer's own words, in English, Japanese and Chinese. The mod's words
    // (its name, choice labels) come from mod-install.json. Log lines stay English
    // so they read the same in a bug report.
    internal static class Strings
    {
        internal enum Key
        {
            Title,
            GameFolder,
            Browse,
            NotFound,
            Running,
            NoPayload,
            BadManifest,
            BepInExHash,
            OtherLoader,
            OtherLoaderNamed,
            RolledBack,
            RolledBackPartly,
            Install,
            Update,
            Uninstall,
            KeepData,
            AlsoBepInEx,
            Installed,
            Uninstalled,
            StatusBepInEx,
            StatusMod,
            Yes,
            No,
            Language,
            Website,
            Working,
            SteamLaunchHint,
            Action,
            NothingToUninstall,
            InstallButton,
            UpdateButton,
            UninstallButton,
            Close,
            InstallWill,
            UninstallWill,
            SmartScreenHint,
            ListAnd,
            ListComma,
            PlanDownloadBepInEx,
            PlanHaveBepInEx,
            PlanFrameworkAndMod,
            PlanMod,
            PlanKeepNewerFramework,
            PlanBackup,
            PlanSet,
            PlanNothingElse,
            PlanOtherLoader,
            PlanOtherLoaderNamed,
            PlanRemovePlugin,
            PlanRemovePluginKeep,
            PlanRemoveConfig,
            PlanRemoveInstallerFolder,
            PlanRemoveFramework,
            PlanKeepFramework,
            PlanRemoveSaveHistory,
            PlanRemoveBepInEx,
            PlanRemoveBepInExKeep,
            PlanKeepBepInEx,
            PlanKeepBepInExUsed,
            Cancel,
            Downloading,
            Cancelled,
            Stopped,
            DownloadFailed,
            DownloadFailedHelp,
            CannotWrite,
            CannotWriteHelp,
            BadZip,
            BadZipHelp,
            SomethingWrong,
            SomethingWrongHelp,
            ShowDetails,
            HideDetails,
            CopyDetails,
            Retry,
            StatusFramework,
            PlanDownloadFramework,
            PlanFrameworkBring,
            PlanFrameworkBringOne,
            PlanFrameworkBringCore,
            PlanFrameworkSatisfied,
            SmartScreenHintFramework,
            InstallingNow,
            DoneList,
            Done,
            DownloadHint,
            StepChecked,
            StepDownload,
            StepDownloading,
            StepHash,
            StepHashBoth,
            StepBackup,
            StepPutBepInEx,
            StepPutBoth,
            StepPut,
            StepSet,
            DoneFramework,
            DoneChecked,
            DoneKeptSame,
            DoneKeptNewer,
            DoneFrameworkSatisfied,
            DoneKeptFramework,
            DoneNotInstalled,
            DoneBepInEx,
            DoneSetting,
            DoneOtherMods,
            DoneOtherModsOne,
            DoneBackup,
            DoneBackupOne,
            PartPreloader,
            ConsentHead,
            ConsentNeedOlder,
            ConsentNeedMissing,
            ConsentNeedParts,
            ConsentWhere,
            ConsentWhereText,
            ConsentWhy,
            ConsentWhyText,
            ConsentSent,
            ConsentSentText,
            ConsentCheck,
            ConsentCheckText,
            ConsentCheckTextBoth,
            ConsentNoApi,
            ConsentNoApiBepInEx,
            OpenReleasePage,
            ChooseZip,
            DownloadAndInstall,
            CancelPlain,
            ChooseZipTitle,
            NetOffline,
            NetBusy,
            NetLimited,
            NetLimitedLater,
            NetTls,
            FwNotPublished,
            FwDownloadFailed,
            FwSize,
            FwHash,
            FwLocalMismatch,
            FwNoDownload,
            BepInExNoDownload,
            FwZipLacks,
            FwZipTooOld,
            FwKeepNotMet,
            NothingChanged,
            FwDeletedHelp,
            FwNotUsedHelp,
            FwManualHelp,
            FwReleaseLink,
            FwKeepLink,
            LaunchOptionCheck,
            PlanLauncher,
            PlanLaunchOptionAdd,
            PlanLaunchOptionHave,
            PlanLaunchOptionRemove,
            PlanRemoveLauncher,
            SteamHead,
            SteamBody,
            SteamBodyRemove,
            SteamKeep,
            SteamClose,
            SteamSelf,
            SteamSkip,
            SteamSkipRemove,
            SteamWaiting,
            SteamClosing,
            SteamSlow,
            DoneLauncher,
            DoneLaunchOptionAdded,
            DoneLaunchOptionRemoved,
            DoneLaunchOptionSkipped,
            DoneLaunchOptionFailed,

            // The window in WebView2 (InstallerSession).
            WebMinimize,
            WebStateSetup,
            WebStateInstalling,
            WebStateUpdating,
            WebStateUninstalling,
            WebStateInstalled,
            WebStateUpdated,
            WebStateUninstalled,
            WebStateFailed,
            WebStateCantStart,
            WebLooking,
            WebFoundIt,
            WebNotFoundIt,
            WebHeadInstall,
            WebHeadUpdate,
            WebHeadReinstall,
            WebHeadUninstall,
            WebLeadInstall,
            WebLeadUpdate,
            WebLeadUninstall,
            WebLeadNotFound,
            WebFound,
            WebLaunchCheck,
            WebLaunchSmall,
            WebLaunchNoSteam,
            WebLaunchNoLauncher,
            WebUpdateWill,
            WebOnline,
            WebNetAsk,
            WebNetLines,
            WebNetNone,
            WebOtherTitle,
            WebOtherText,
            WebOtherTextNamed,
            WebOtherFoot,
            WebSheetStop,
            WebStepCheck,
            WebStepCheckSmall,
            WebStepDownload,
            WebStepFrom,
            WebStepHashSmall,
            WebStepBackup,
            WebStepPutSmall,
            WebStepLaunchAdd,
            WebStepLaunchAddSmall,
            WebStepLaunchRemove,
            WebStepLaunchRemoveSmall,
            WebPhaseCheck,
            WebPhaseDownload,
            WebPhaseVerify,
            WebPhaseBackup,
            WebPhasePut,
            WebPhaseSet,
            WebPhaseLaunch,
            WebPhaseDone,
            WebPhaseRemove,
            WebPhaseRemoved,
            WebPhaseRollback,
            WebSubGame,
            WebNetNotYet,
            WebNetWriting,
            WebNetUninstall,
            WebNetStopping,
            WebWorkInstall,
            WebWorkUpdate,
            WebWorkUninstall,
            WebDoneInstall,
            WebDoneUpdate,
            WebDoneUninstall,
            WebDoneLead,
            WebDoneLeadUninstall,
            WebDoneList,
            WebReady,
            WebReadyLauncher,
            WebReadySteam,
            WebUninstalledSmall,
            WebStart,
            WebLog,
            WebPillSame,
            WebPillBack,
            WebPillPartly,
            WebDetails,
            WebCopied,
            WebBack,
        }

        private static readonly Dictionary<string, Dictionary<Key, string>> All = new Dictionary<string, Dictionary<Key, string>>
        {
            ["en"] = new Dictionary<Key, string>
            {
                [Key.Title] = "{0} installer",
                [Key.GameFolder] = "Game folder",
                [Key.Browse] = "Browse...",
                [Key.NotFound] = "Couldn't find Drag'n Wash. Choose the game folder (the one with DragNWash.exe).",
                [Key.Running] = "Close the game first.",
                [Key.NoPayload] = "The mod's files aren't next to the installer. Extract the whole zip first, then run Install.exe from the extracted folder.",
                [Key.BadManifest] = "Couldn't read the mod-install.json next to the installer.",
                [Key.BepInExHash] = "The BepInEx download is broken or has been tampered with (SHA-256 mismatch). Nothing was installed.",
                [Key.OtherLoader] = "There's another mod loader in this game folder. A game folder can only have one loader, so nothing was changed.",
                [Key.OtherLoaderNamed] = "There's another mod loader ({0}) in this game folder. A game folder can only have one loader, so nothing was changed.",
                [Key.RolledBack] = "Something went wrong while copying, so everything was put back the way it was ({0} files).",
                [Key.RolledBackPartly] = "Something went wrong while copying, and {0} files couldn't be put back. The files it replaced are kept in {1}.",
                [Key.Install] = "Install",
                [Key.Update] = "Update",
                [Key.Uninstall] = "Uninstall",
                [Key.KeepData] = "Keep save history and the mod's working files",
                [Key.AlsoBepInEx] = "Also remove BepInEx if no other mods are left",
                [Key.Installed] = "All done. Start the game from Steam.",
                [Key.Uninstalled] = "Uninstalled.",
                [Key.StatusBepInEx] = "BepInEx",
                [Key.StatusMod] = "Installed version",
                [Key.Yes] = "installed",
                [Key.No] = "not installed",
                [Key.Language] = "Installer language",
                [Key.Website] = "Website",
                [Key.Working] = "Working...",
                [Key.SteamLaunchHint] = "You can also uninstall mods in the game, under Options → Mods.",
                [Key.Action] = "Action",
                [Key.NothingToUninstall] = "(nothing to uninstall)",
                [Key.InstallButton] = "&Install",
                [Key.UpdateButton] = "&Update",
                [Key.UninstallButton] = "&Uninstall",
                [Key.Close] = "&Close",
                [Key.InstallWill] = "Install will:",
                [Key.UninstallWill] = "Uninstall will:",
                [Key.SmartScreenHint] = "Windows SmartScreen or Defender may warn you about Install.exe because it isn't code-signed. It only does what's in the list above.",
                [Key.ListAnd] = " and ",
                [Key.ListComma] = ", ",
                [Key.PlanDownloadBepInEx] = "Download BepInEx {0} from {1} (served by {2}) and check its SHA-256",
                [Key.PlanHaveBepInEx] = "Use the BepInEx that's already in the game folder",
                [Key.PlanFrameworkAndMod] = "Put Drag'n Wash ModFramework {0} and {1} into BepInEx\\plugins (anything you added there stays)",
                [Key.PlanMod] = "Put {0} into BepInEx\\plugins (anything you added there stays)",
                [Key.PlanKeepNewerFramework] = "Keep Drag'n Wash ModFramework {0}, since it's newer than the one in this zip",
                [Key.PlanBackup] = "Back up every file it replaces to BepInEx\\DragNWash.Installer\\backup first",
                [Key.PlanSet] = "Set {0} = {1} in BepInEx\\config\\{2}",
                [Key.PlanNothingElse] = "Nothing else gets downloaded or changed.",
                [Key.PlanOtherLoader] = "Stop without changing anything, because there's another mod loader in this game folder and a game folder can only have one",
                [Key.PlanOtherLoaderNamed] = "Stop without changing anything, because there's another mod loader ({0}) in this game folder and a game folder can only have one",
                [Key.PlanRemovePlugin] = "Remove BepInEx\\plugins\\{0}",
                [Key.PlanRemovePluginKeep] = "Remove BepInEx\\plugins\\{0}, but keep {1}",
                [Key.PlanRemoveConfig] = "Remove BepInEx\\config\\{0}",
                [Key.PlanRemoveInstallerFolder] = "Remove the installer's backup in BepInEx\\DragNWash.Installer",
                [Key.PlanRemoveFramework] = "Remove Drag'n Wash ModFramework too, since no other mod uses it",
                [Key.PlanKeepFramework] = "Keep Drag'n Wash ModFramework, since other mods still use it: {0}",
                [Key.PlanRemoveSaveHistory] = "Remove the save history in BepInEx\\SaveHistory",
                [Key.PlanRemoveBepInEx] = "Remove BepInEx",
                [Key.PlanRemoveBepInExKeep] = "Remove BepInEx, but leave the data you're keeping in the BepInEx folder",
                [Key.PlanKeepBepInEx] = "Keep BepInEx",
                [Key.PlanKeepBepInExUsed] = "Keep BepInEx, since other mods or patchers use it",
                [Key.Cancel] = "&Cancel",
                [Key.Downloading] = "Downloading {0} from {1}",
                [Key.Cancelled] = "Cancelled. Nothing was changed in the game folder.",
                [Key.Stopped] = "Stopped.",
                [Key.DownloadFailed] = "Couldn't download BepInEx.",
                [Key.DownloadFailedHelp] = "Check your internet connection and try again. Nothing in the game folder was changed.",
                [Key.CannotWrite] = "Couldn't write to the game folder.",
                [Key.CannotWriteHelp] = "A file there might be in use or read-only. Close the game and anything else using its folder, then try again.",
                [Key.BadZip] = "The download isn't a valid zip.",
                [Key.BadZipHelp] = "Try again. If it keeps happening, copy the details into a bug report.",
                [Key.SomethingWrong] = "Something went wrong.",
                [Key.SomethingWrongHelp] = "Please copy the details into a bug report on the mod's website.",
                [Key.ShowDetails] = "Show details",
                [Key.HideDetails] = "Hide details",
                [Key.CopyDetails] = "Copy &details",
                [Key.Retry] = "&Retry",
                [Key.StatusFramework] = "ModFramework",
                [Key.PlanDownloadFramework] = "Download Drag'n Wash ModFramework {0} from {1} (served by {2}) and check its SHA-256",
                [Key.PlanFrameworkBring] = "Bring the framework core and the {0} libraries this mod uses up to {1} (newer ones already there stay)",
                [Key.PlanFrameworkBringOne] = "Bring the framework core and the library this mod uses up to {1} (a newer one already there stays)",
                [Key.PlanFrameworkBringCore] = "Bring the framework core up to {1} (a newer one already there stays)",
                [Key.PlanFrameworkSatisfied] = "Keep Drag'n Wash ModFramework {0}. It already has everything this mod needs, so nothing gets downloaded",
                [Key.SmartScreenHintFramework] = "Windows SmartScreen or Defender may warn you about Install.exe because it isn't code-signed and it downloads ModFramework from the internet. It only does what's in the list above.",
                [Key.InstallingNow] = "Installing:",
                [Key.DoneList] = "Done:",
                [Key.Done] = "Done.",
                [Key.DownloadHint] = "The game folder isn't touched until the download has been checked, so Cancel leaves it as it was.",
                [Key.StepChecked] = "Checked what's installed: ModFramework {0}, BepInEx {1}, no other mod loader",
                [Key.StepDownload] = "Download {0} from {1}",
                [Key.StepDownloading] = "Downloading {0} of {1}: {2} ({3} KB of {4} KB)",
                [Key.StepHash] = "Check its SHA-256",
                [Key.StepHashBoth] = "Check their SHA-256",
                [Key.StepBackup] = "Back up the files it replaces to BepInEx\\DragNWash.Installer\\backup",
                [Key.StepPutBepInEx] = "Put BepInEx {0} into the game folder",
                [Key.StepPutBoth] = "Put ModFramework and {0} into BepInEx\\plugins",
                [Key.StepPut] = "Put {0} into BepInEx\\plugins",
                [Key.StepSet] = "Set {0} = {1}",
                [Key.DoneFramework] = "ModFramework {0}: {1}",
                [Key.DoneChecked] = " (SHA-256 checked)",
                [Key.DoneKeptSame] = "Kept {0}: it's already the same version",
                [Key.DoneKeptNewer] = "Kept {0}: it's newer than the one in ModFramework {1}",
                [Key.DoneFrameworkSatisfied] = "ModFramework {0}: already has everything this mod needs, so nothing was downloaded",
                [Key.DoneKeptFramework] = "Kept ModFramework {0}: it meets this mod's minimums",
                [Key.DoneNotInstalled] = "Not installed: {0} (this mod doesn't use them)",
                [Key.DoneBepInEx] = "BepInEx {0} (SHA-256 checked)",
                [Key.DoneSetting] = "{0} = {1}",
                [Key.DoneOtherMods] = "Other mods: {0} folders in BepInEx\\plugins, left alone",
                [Key.DoneOtherModsOne] = "Other mods: 1 folder in BepInEx\\plugins, left alone",
                [Key.DoneBackup] = "The {0} replaced files are kept in {1}",
                [Key.DoneBackupOne] = "The replaced file is kept in {1}",
                [Key.PartPreloader] = "the Preloader",
                [Key.ConsentHead] = "The installer is going to connect to the internet",
                [Key.ConsentNeedOlder] = "This mod needs Drag'n Wash ModFramework {0}, but the game folder has {1}. The installer will get it from the framework's release on GitHub.",
                [Key.ConsentNeedMissing] = "This mod needs Drag'n Wash ModFramework {0}, and it isn't in the game folder. The installer will get it from the framework's release on GitHub.",
                [Key.ConsentNeedParts] = "This mod needs parts of Drag'n Wash ModFramework {0} that aren't in the game folder. The installer will get them from the framework's release on GitHub.",
                [Key.ConsentWhere] = "Where",
                [Key.ConsentWhereText] = "github.com (the releases of {0})\r\n{1} (GitHub stores the file there, and github.com sends the installer over)",
                [Key.ConsentWhy] = "Why",
                [Key.ConsentWhyText] = "To get {0}, just this once.",
                [Key.ConsentSent] = "Sent",
                [Key.ConsentSentText] = "Just a normal HTTPS request with the User-Agent {0}. Your name, your folders, sign-ins and cookies aren't sent. Like any website you visit, GitHub does see your IP address.",
                [Key.ConsentCheck] = "Check",
                [Key.ConsentCheckText] = "It's only used if its SHA-256 matches the one in this mod's release. Until then, nothing in the game folder changes.",
                [Key.ConsentCheckTextBoth] = "Each one is only used if its SHA-256 matches the one in this mod's release (ModFramework) or in the installer (BepInEx). Until then, nothing in the game folder changes.",
                [Key.ConsentNoApi] = "It doesn't contact api.github.com. If you pick a zip you downloaded yourself, it doesn't use the internet at all.",
                [Key.ConsentNoApiBepInEx] = "It doesn't contact api.github.com. If you pick a ModFramework zip you downloaded yourself, it still downloads BepInEx.",
                [Key.OpenReleasePage] = "Open the release page",
                [Key.ChooseZip] = "Choose &zip...",
                [Key.DownloadAndInstall] = "&Download and install",
                [Key.CancelPlain] = "Cancel",
                [Key.ChooseZipTitle] = "Choose {0}",
                [Key.NetOffline] = "The installer can't reach the internet.",
                [Key.NetBusy] = "GitHub didn't answer, or answered with an error. Try again in a few minutes.",
                [Key.NetLimited] = "GitHub is limiting downloads right now. Try again in {0} minutes.",
                [Key.NetLimitedLater] = "GitHub is limiting downloads right now. Try again later.",
                [Key.NetTls] = "Couldn't confirm a secure connection to GitHub.",
                [Key.FwNotPublished] = "ModFramework {0} isn't published yet. Please let the mod's author know.",
                [Key.FwDownloadFailed] = "Couldn't download ModFramework {0}.",
                [Key.FwSize] = "The downloaded ModFramework {0} isn't the size this mod's release says it should be.",
                [Key.FwHash] = "The downloaded ModFramework {0} doesn't match the one in this mod's release (SHA-256).",
                [Key.FwLocalMismatch] = "The zip you chose isn't the ModFramework {0} this mod's release names (size or SHA-256).",
                [Key.FwNoDownload] = "ModFramework {0} needs to be downloaded, but downloads are turned off (--no-download). Pass the zip with --framework-zip.",
                [Key.BepInExNoDownload] = "BepInEx {0} needs to be downloaded, but downloads are turned off (--no-download). Pass the zip with --bepinex-zip.",
                [Key.FwZipLacks] = "ModFramework {0} doesn't have {1}, which this mod needs. Please let the mod's author know.",
                [Key.FwZipTooOld] = "ModFramework {0} has {1} {2}, but this mod needs {3} or newer. Please let the mod's author know.",
                [Key.FwKeepNotMet] = "The ModFramework you have doesn't meet this mod's minimums, so ModFramework {0} has to be installed.",
                [Key.NothingChanged] = "Nothing was changed in the game folder.",
                [Key.FwDeletedHelp] = "The file wasn't used and has been deleted. Nothing in the game folder was changed.",
                [Key.FwNotUsedHelp] = "The zip wasn't used. Nothing in the game folder was changed.",
                [Key.FwManualHelp] = "You can also download the zip yourself from the release page and pick it with “Choose zip”. It gets checked the same way.",
                [Key.FwReleaseLink] = "Open the release page ({0})",
                [Key.FwKeepLink] = "Just install the mod and keep ModFramework {0} (it meets this mod's minimums)",
                [Key.LaunchOptionCheck] = "Check for mod updates when the game starts (sets the Steam launch option)",
                [Key.PlanLauncher] = "Put the update launcher (Launcher.exe) into BepInEx\\DragNWash.Installer",
                [Key.PlanLaunchOptionAdd] = "Add the update launcher to the game's launch options in Steam (launch options you already have stay)",
                [Key.PlanLaunchOptionHave] = "The update launcher is already in the game's launch options in Steam",
                [Key.PlanLaunchOptionRemove] = "Take the update launcher out of the game's launch options in Steam (your other launch options stay)",
                [Key.PlanRemoveLauncher] = "Remove the update launcher (Launcher.exe and its files) from BepInEx\\DragNWash.Installer",
                [Key.SteamHead] = "Close Steam first",
                [Key.SteamBody] = "Steam is running. To set the launch option, the installer changes one of Steam's settings files, and Steam writes over that file while it's open.",
                [Key.SteamBodyRemove] = "Steam is running. To change the launch option, the installer changes one of Steam's settings files, and Steam writes over that file while it's open.",
                [Key.SteamKeep] = "Launch options you already have are kept.",
                [Key.SteamClose] = "Close Steam for me",
                [Key.SteamSelf] = "I'll close it",
                [Key.SteamSkip] = "Skip this option",
                [Key.SteamSkipRemove] = "Leave it as it is",
                [Key.SteamWaiting] = "Waiting for Steam to close... The installer carries on by itself once it has.",
                [Key.SteamClosing] = "Closing Steam... The installer carries on by itself once it has.",
                [Key.SteamSlow] = "Steam still hasn't closed after {0} seconds. Close it yourself (Steam menu, then Exit), or carry on without changing the launch option this time.",
                [Key.DoneLauncher] = "Update launcher: put in BepInEx\\DragNWash.Installer",
                [Key.DoneLaunchOptionAdded] = "Steam launch options: the update launcher was added (the ones you had stay)",
                [Key.DoneLaunchOptionRemoved] = "Steam launch options: the update launcher was taken out",
                [Key.DoneLaunchOptionSkipped] = "Steam launch options: left as they were",
                [Key.DoneLaunchOptionFailed] = "Steam launch options: couldn't be changed (the log says why)",
                [Key.WebMinimize] = "Minimize",
                [Key.WebStateSetup] = "Installer",
                [Key.WebStateInstalling] = "Installing",
                [Key.WebStateUpdating] = "Updating",
                [Key.WebStateUninstalling] = "Uninstalling",
                [Key.WebStateInstalled] = "Installed",
                [Key.WebStateUpdated] = "Updated",
                [Key.WebStateUninstalled] = "Uninstalled",
                [Key.WebStateFailed] = "Didn't work",
                [Key.WebStateCantStart] = "Can't start",
                [Key.WebLooking] = "Looking for the game folder",
                [Key.WebFoundIt] = "Found it",
                [Key.WebNotFoundIt] = "Couldn't find it",
                [Key.WebHeadInstall] = "Install {0}",
                [Key.WebHeadUpdate] = "Update from {0} to {1}",
                [Key.WebHeadReinstall] = "Put {0} in again",
                [Key.WebHeadUninstall] = "Uninstall {0}",
                [Key.WebLeadInstall] = "Check the folder and the list on the right. If it looks right, press Install.",
                [Key.WebLeadUpdate] = "Your settings carry over. If the list on the right looks right, press Update.",
                [Key.WebLeadUninstall] = "Pick what to keep. If the list on the right looks right, press Uninstall.",
                [Key.WebLeadNotFound] = "Choose the game folder first.",
                [Key.WebFound] = "Found",
                [Key.WebLaunchCheck] = "Check for mod updates when the game starts",
                [Key.WebLaunchSmall] = "Sets the Steam launch option",
                [Key.WebLaunchNoSteam] = "No Steam account found, so this can't be set",
                [Key.WebLaunchNoLauncher] = "The update launcher doesn't come with this install, so this can't be set",
                [Key.WebUpdateWill] = "Update will:",
                [Key.WebOnline] = "online",
                [Key.WebNetAsk] = "Only the lines marked “online” use the internet, and you get asked once more before that.",
                [Key.WebNetLines] = "Only the lines marked “online” use the internet.",
                [Key.WebNetNone] = "Doesn't use the internet.",
                [Key.WebOtherTitle] = "Another mod loader is in this folder",
                [Key.WebOtherText] = "There's another mod loader here. A game folder can only have one loader, so it can't be installed to this folder.",
                [Key.WebOtherTextNamed] = "{0} is here. A game folder can only have one loader, so it can't be installed to this folder.",
                [Key.WebOtherFoot] = "Another mod loader is here, so it can't be installed.",
                [Key.WebSheetStop] = "Stop (nothing is changed)",
                [Key.WebStepCheck] = "Check what's installed",
                [Key.WebStepCheckSmall] = "ModFramework: {0}, BepInEx: {1}, no other mod loader",
                [Key.WebStepDownload] = "Download {0}",
                [Key.WebStepFrom] = "from {0}",
                [Key.WebStepHashSmall] = "Makes sure the files arrived whole",
                [Key.WebStepBackup] = "Back up",
                [Key.WebStepPutSmall] = "Other mods are left alone",
                [Key.WebStepLaunchAdd] = "Set the Steam launch option",
                [Key.WebStepLaunchAddSmall] = "Adds the update launcher",
                [Key.WebStepLaunchRemove] = "Take it out of the Steam launch options",
                [Key.WebStepLaunchRemoveSmall] = "Your other launch options stay",
                [Key.WebPhaseCheck] = "Checking",
                [Key.WebPhaseDownload] = "Downloading",
                [Key.WebPhaseVerify] = "Checking SHA-256",
                [Key.WebPhaseBackup] = "Taking a backup",
                [Key.WebPhasePut] = "Putting files in",
                [Key.WebPhaseSet] = "Setting it up",
                [Key.WebPhaseLaunch] = "Setting the Steam launch option",
                [Key.WebPhaseDone] = "All in",
                [Key.WebPhaseRemove] = "Removing",
                [Key.WebPhaseRemoved] = "All removed",
                [Key.WebPhaseRollback] = "Putting everything back",
                [Key.WebSubGame] = "Game folder: {0}",
                [Key.WebNetNotYet] = "Nothing in the game folder has changed yet, so Cancel leaves it as it was.",
                [Key.WebNetWriting] = "From here on the game folder is being changed, so it can't be cancelled. If something fails, everything is put back.",
                [Key.WebNetUninstall] = "This only takes a moment.",
                [Key.WebNetStopping] = "Stopping the download. Nothing in the game folder has changed.",
                [Key.WebWorkInstall] = "Putting {0} {1} in.",
                [Key.WebWorkUpdate] = "Bringing {0} up to {1}.",
                [Key.WebWorkUninstall] = "Taking {0} out.",
                [Key.WebDoneInstall] = "All installed",
                [Key.WebDoneUpdate] = "All updated",
                [Key.WebDoneUninstall] = "Uninstalled",
                [Key.WebDoneLead] = "Press Start the game to play right away.",
                [Key.WebDoneLeadUninstall] = "Taken out of the game folder.",
                [Key.WebDoneList] = "What was done",
                [Key.WebReady] = "Ready to play",
                [Key.WebReadyLauncher] = "When it starts, it checks for updates first",
                [Key.WebReadySteam] = "Steam starts it as usual",
                [Key.WebUninstalledSmall] = "To put it back, run this Install.exe again",
                [Key.WebStart] = "Start the game",
                [Key.WebLog] = "Log",
                [Key.WebPillSame] = "Your game folder is just as it was (nothing was changed)",
                [Key.WebPillBack] = "Your game folder is just as it was (put back, {0} files)",
                [Key.WebPillPartly] = "{0} files couldn't be put back",
                [Key.WebDetails] = "Details",
                [Key.WebCopied] = "Copied",
                [Key.WebBack] = "Back",
            },
            ["ja"] = new Dictionary<Key, string>
            {
                [Key.Title] = "{0} インストーラー",
                [Key.GameFolder] = "ゲームのフォルダー",
                [Key.Browse] = "参照...",
                [Key.NotFound] = "Drag'n Wash が見つかりませんでした。ゲームのフォルダー（DragNWash.exe が入っているところ）を選んでください。",
                [Key.Running] = "先にゲームを閉じてください。",
                [Key.NoPayload] = "インストーラーと同じ場所に Mod のファイルがありません。先に zip を丸ごと展開して、展開したフォルダーの Install.exe を起動してください。",
                [Key.BadManifest] = "インストーラーの隣にある mod-install.json が読めませんでした。",
                [Key.BepInExHash] = "ダウンロードした BepInEx が壊れているか、手を加えられています（SHA-256 が合いません）。何もインストールしていません。",
                [Key.OtherLoader] = "このゲームのフォルダーには別の Mod ローダーが入っています。ローダーは 1 つのゲームフォルダーに 1 つしか入れられないので、何も変えていません。",
                [Key.OtherLoaderNamed] = "このゲームのフォルダーには別の Mod ローダー（{0}）が入っています。ローダーは 1 つのゲームフォルダーに 1 つしか入れられないので、何も変えていません。",
                [Key.RolledBack] = "コピーの途中でうまくいかなかったので、全部元に戻しました（{0} ファイル）。",
                [Key.RolledBackPartly] = "コピーの途中でうまくいかず、{0} ファイルは元に戻せませんでした。上書きしたファイルの控えは {1} に残っています。",
                [Key.Install] = "インストール",
                [Key.Update] = "更新",
                [Key.Uninstall] = "アンインストール",
                [Key.KeepData] = "セーブ履歴と Mod の作業ファイルは残す",
                [Key.AlsoBepInEx] = "ほかに Mod が残っていなければ BepInEx も削除する",
                [Key.Installed] = "インストールが終わりました。Steam からゲームを起動してください。",
                [Key.Uninstalled] = "アンインストールしました。",
                [Key.StatusBepInEx] = "BepInEx",
                [Key.StatusMod] = "入っているバージョン",
                [Key.Yes] = "あり",
                [Key.No] = "なし",
                [Key.Language] = "インストーラーの言語",
                [Key.Website] = "Web サイト",
                [Key.Working] = "作業中...",
                [Key.SteamLaunchHint] = "Mod はゲームの中の Options → Mods からもアンインストールできます。",
                [Key.Action] = "操作",
                [Key.NothingToUninstall] = "（アンインストールするものはありません）",
                [Key.InstallButton] = "インストール(&I)",
                [Key.UpdateButton] = "更新(&U)",
                [Key.UninstallButton] = "アンインストール(&U)",
                [Key.Close] = "閉じる(&C)",
                [Key.InstallWill] = "インストールですること：",
                [Key.UninstallWill] = "アンインストールですること：",
                [Key.SmartScreenHint] = "Install.exe にはコード署名がないので、Windows SmartScreen や Defender に警告されることがあります。やるのは上の一覧に書いたことだけです。",
                [Key.ListAnd] = " と ",
                [Key.ListComma] = "、",
                [Key.PlanDownloadBepInEx] = "BepInEx {0} を {1}（転送先 {2}）からダウンロードして、SHA-256 を確かめる",
                [Key.PlanHaveBepInEx] = "ゲームのフォルダーにもう入っている BepInEx を使う",
                [Key.PlanFrameworkAndMod] = "Drag'n Wash ModFramework {0} と {1} を BepInEx\\plugins に入れる（自分で足したファイルはそのまま）",
                [Key.PlanMod] = "{0} を BepInEx\\plugins に入れる（自分で足したファイルはそのまま）",
                [Key.PlanKeepNewerFramework] = "Drag'n Wash ModFramework {0} はこの zip のものより新しいので、そのまま残す",
                [Key.PlanBackup] = "上書きするファイルは、先に BepInEx\\DragNWash.Installer\\backup に控えておく",
                [Key.PlanSet] = "「{0}」を「{1}」に設定する（BepInEx\\config\\{2}）",
                [Key.PlanNothingElse] = "これ以外に、ダウンロードしたり変えたりするものはありません。",
                [Key.PlanOtherLoader] = "別の Mod ローダーが入っているので、何も変えずに止める（ローダーは 1 つのゲームフォルダーに 1 つだけ）",
                [Key.PlanOtherLoaderNamed] = "別の Mod ローダー（{0}）が入っているので、何も変えずに止める（ローダーは 1 つのゲームフォルダーに 1 つだけ）",
                [Key.PlanRemovePlugin] = "BepInEx\\plugins\\{0} を削除する",
                [Key.PlanRemovePluginKeep] = "BepInEx\\plugins\\{0} を削除する（{1} は残す）",
                [Key.PlanRemoveConfig] = "BepInEx\\config\\{0} を削除する",
                [Key.PlanRemoveInstallerFolder] = "BepInEx\\DragNWash.Installer にあるインストーラーの控えを削除する",
                [Key.PlanRemoveFramework] = "ほかに使っている Mod がないので、Drag'n Wash ModFramework も削除する",
                [Key.PlanKeepFramework] = "ほかの Mod（{0}）が使っているので、Drag'n Wash ModFramework は残す",
                [Key.PlanRemoveSaveHistory] = "BepInEx\\SaveHistory のセーブ履歴を削除する",
                [Key.PlanRemoveBepInEx] = "BepInEx を削除する",
                [Key.PlanRemoveBepInExKeep] = "BepInEx を削除する（残すデータは BepInEx フォルダーにそのまま置いておく）",
                [Key.PlanKeepBepInEx] = "BepInEx は残す",
                [Key.PlanKeepBepInExUsed] = "ほかの Mod かパッチャーが使っているので、BepInEx は残す",
                [Key.Cancel] = "キャンセル(&C)",
                [Key.Downloading] = "{0} を {1} からダウンロードしています",
                [Key.Cancelled] = "キャンセルしました。ゲームのフォルダーは何も変わっていません。",
                [Key.Stopped] = "止めました。",
                [Key.DownloadFailed] = "BepInEx をダウンロードできませんでした。",
                [Key.DownloadFailedHelp] = "インターネットにつながっているか確かめて、もう一度試してください。ゲームのフォルダーは何も変わっていません。",
                [Key.CannotWrite] = "ゲームのフォルダーに書き込めませんでした。",
                [Key.CannotWriteHelp] = "中のファイルが使われているか、読み取り専用になっているのかもしれません。ゲームと、そのフォルダーを使っているほかのプログラムを閉じてから、もう一度試してください。",
                [Key.BadZip] = "ダウンロードしたファイルが、ちゃんとした zip になっていません。",
                [Key.BadZipHelp] = "もう一度試してみてください。何度やってもだめなら、詳細をコピーしてバグ報告に貼ってください。",
                [Key.SomethingWrong] = "問題が起きました。",
                [Key.SomethingWrongHelp] = "詳細をコピーして、Mod の Web サイトのバグ報告に貼ってください。",
                [Key.ShowDetails] = "詳細を表示",
                [Key.HideDetails] = "詳細を隠す",
                [Key.CopyDetails] = "詳細をコピー(&D)",
                [Key.Retry] = "再試行(&R)",
                [Key.StatusFramework] = "ModFramework",
                [Key.PlanDownloadFramework] = "Drag'n Wash ModFramework {0} を {1}（転送先 {2}）からダウンロードして、SHA-256 を確かめる",
                [Key.PlanFrameworkBring] = "ModFramework の core と、この Mod が使う {0} つのライブラリを {1} にそろえる（もっと新しいものが入っていれば、そのまま）",
                [Key.PlanFrameworkBringOne] = "ModFramework の core と、この Mod が使うライブラリを {1} にそろえる（もっと新しいものが入っていれば、そのまま）",
                [Key.PlanFrameworkBringCore] = "ModFramework の core を {1} にそろえる（もっと新しいものが入っていれば、そのまま）",
                [Key.PlanFrameworkSatisfied] = "Drag'n Wash ModFramework {0} にこの Mod に要るものがそろっているので、ダウンロードせずにそのまま使う",
                [Key.SmartScreenHintFramework] = "Install.exe にはコード署名がなく、ModFramework をネットから取ってくるので、Windows SmartScreen や Defender に警告されることがあります。やるのは上の一覧に書いたことだけです。",
                [Key.InstallingNow] = "インストール中：",
                [Key.DoneList] = "やったこと：",
                [Key.Done] = "終わりました。",
                [Key.DownloadHint] = "ダウンロードしたものを確かめ終わるまでゲームのフォルダーには手を付けないので、キャンセルしても元のままです。",
                [Key.StepChecked] = "入っているものを確かめた：ModFramework {0}、BepInEx {1}、ほかのローダーなし",
                [Key.StepDownload] = "{0} を {1} からダウンロードする",
                [Key.StepDownloading] = "ダウンロード中 {0} / {1}：{2}（{3} KB / {4} KB）",
                [Key.StepHash] = "SHA-256 を確かめる",
                [Key.StepHashBoth] = "SHA-256 を確かめる",
                [Key.StepBackup] = "上書きするファイルを BepInEx\\DragNWash.Installer\\backup に控えておく",
                [Key.StepPutBepInEx] = "BepInEx {0} をゲームのフォルダーに入れる",
                [Key.StepPutBoth] = "ModFramework と {0} を BepInEx\\plugins に入れる",
                [Key.StepPut] = "{0} を BepInEx\\plugins に入れる",
                [Key.StepSet] = "「{0}」を「{1}」に設定する",
                [Key.DoneFramework] = "ModFramework {0}：{1}",
                [Key.DoneChecked] = "（SHA-256 確認済み）",
                [Key.DoneKeptSame] = "{0} は同じバージョンなので、そのまま",
                [Key.DoneKeptNewer] = "{0} は ModFramework {1} のものより新しいので、そのまま",
                [Key.DoneFrameworkSatisfied] = "ModFramework {0} にこの Mod に要るものがそろっていたので、ダウンロードはしていません",
                [Key.DoneKeptFramework] = "ModFramework {0} はこの Mod の最低条件を満たしているので、そのまま",
                [Key.DoneNotInstalled] = "入れなかったもの：{0}（この Mod は使いません）",
                [Key.DoneBepInEx] = "BepInEx {0}（SHA-256 確認済み）",
                [Key.DoneSetting] = "「{0}」＝「{1}」",
                [Key.DoneOtherMods] = "ほかの Mod：BepInEx\\plugins の {0} フォルダーには触っていません",
                [Key.DoneOtherModsOne] = "ほかの Mod：BepInEx\\plugins の 1 フォルダーには触っていません",
                [Key.DoneBackup] = "上書きした {0} ファイルの控えは {1} にあります",
                [Key.DoneBackupOne] = "上書きした 1 ファイルの控えは {1} にあります",
                [Key.PartPreloader] = "Preloader",
                [Key.ConsentHead] = "インターネットにつなぎます",
                [Key.ConsentNeedOlder] = "この Mod を動かすには Drag'n Wash ModFramework {0} が要りますが、ゲームのフォルダーに入っているのは {1} です。GitHub のリリースページから取ってきます。",
                [Key.ConsentNeedMissing] = "この Mod を動かすには Drag'n Wash ModFramework {0} が要りますが、ゲームのフォルダーに入っていません。GitHub のリリースページから取ってきます。",
                [Key.ConsentNeedParts] = "この Mod を動かすには Drag'n Wash ModFramework {0} の一部が要りますが、ゲームのフォルダーに入っていません。GitHub のリリースページから取ってきます。",
                [Key.ConsentWhere] = "つなぐ先",
                [Key.ConsentWhereText] = "github.com（{0} のリリース）\r\n{1}（GitHub がファイルを置いているところで、github.com から自動でここに回されます）",
                [Key.ConsentWhy] = "理由",
                [Key.ConsentWhyText] = "{0} を 1 回だけ取ってくるためです。",
                [Key.ConsentSent] = "送るもの",
                [Key.ConsentSentText] = "送るのは普通の HTTPS のリクエストと User-Agent（{0}）だけで、名前やフォルダーの場所、ログイン情報、Cookie は送りません。ただ、どのサイトを見るときもそうですが、GitHub 側には IP アドレスが見えます。",
                [Key.ConsentCheck] = "確かめ方",
                [Key.ConsentCheckText] = "取ってきたファイルは、SHA-256 がこの Mod のリリースに書かれた値と合ったときだけ使います。確認が済むまで、ゲームのフォルダーには手を付けません。",
                [Key.ConsentCheckTextBoth] = "取ってきたファイルはどちらも、SHA-256 がこの Mod のリリース（ModFramework）かインストーラー（BepInEx）に書かれた値と合ったときだけ使います。確認が済むまで、ゲームのフォルダーには手を付けません。",
                [Key.ConsentNoApi] = "api.github.com にはつなぎません。自分でダウンロードした zip を選べば、ネットを使わずに入れられます。",
                [Key.ConsentNoApiBepInEx] = "api.github.com にはつなぎません。自分でダウンロードした ModFramework の zip を選んだときも、BepInEx はダウンロードします。",
                [Key.OpenReleasePage] = "リリースページを開く",
                [Key.ChooseZip] = "zip を選ぶ(&Z)...",
                [Key.DownloadAndInstall] = "ダウンロードしてインストール(&D)",
                [Key.CancelPlain] = "キャンセル",
                [Key.ChooseZipTitle] = "{0} を選ぶ",
                [Key.NetOffline] = "インターネットにつながりません。",
                [Key.NetBusy] = "GitHub から返事がないか、エラーが返ってきました。数分たってからもう一度試してください。",
                [Key.NetLimited] = "GitHub のダウンロード制限にかかっています。{0} 分たってからもう一度試してください。",
                [Key.NetLimitedLater] = "GitHub のダウンロード制限にかかっています。しばらくたってからもう一度試してください。",
                [Key.NetTls] = "GitHub と安全につながっているか確かめられませんでした。",
                [Key.FwNotPublished] = "ModFramework {0} はまだ公開されていません。Mod の作者に知らせてください。",
                [Key.FwDownloadFailed] = "ModFramework {0} をダウンロードできませんでした。",
                [Key.FwSize] = "ダウンロードした ModFramework {0} のサイズが、この Mod のリリースに書かれたものと違います。",
                [Key.FwHash] = "ダウンロードした ModFramework {0} が、この Mod のリリースに書かれたものと合いません（SHA-256）。",
                [Key.FwLocalMismatch] = "選んだ zip は、この Mod のリリースに書かれた ModFramework {0} ではありません（サイズか SHA-256 が違います）。",
                [Key.FwNoDownload] = "ModFramework {0} をダウンロードしないといけませんが、ダウンロードがオフになっています（--no-download）。--framework-zip で zip を渡してください。",
                [Key.BepInExNoDownload] = "BepInEx {0} をダウンロードしないといけませんが、ダウンロードがオフになっています（--no-download）。--bepinex-zip で zip を渡してください。",
                [Key.FwZipLacks] = "ModFramework {0} に、この Mod に要る {1} が入っていません。Mod の作者に知らせてください。",
                [Key.FwZipTooOld] = "ModFramework {0} の {1} は {2} ですが、この Mod には {3} 以上が要ります。Mod の作者に知らせてください。",
                [Key.FwKeepNotMet] = "入っている ModFramework ではこの Mod の最低条件に届かないので、ModFramework {0} を入れる必要があります。",
                [Key.NothingChanged] = "ゲームのフォルダーは何も変わっていません。",
                [Key.FwDeletedHelp] = "ファイルは使わずに消しました。ゲームのフォルダーは何も変わっていません。",
                [Key.FwNotUsedHelp] = "zip は使っていません。ゲームのフォルダーは何も変わっていません。",
                [Key.FwManualHelp] = "リリースページから zip を自分でダウンロードして、「zip を選ぶ」で選ぶこともできます。そのときも同じように確かめます。",
                [Key.FwReleaseLink] = "リリースページを開く（{0}）",
                [Key.FwKeepLink] = "ModFramework {0} はそのままで、Mod だけ入れる（この Mod の最低条件は満たしています）",
                [Key.LaunchOptionCheck] = "起動時に更新を確認する（Steam の起動オプションを設定）",
                [Key.PlanLauncher] = "更新用のランチャー（Launcher.exe）を BepInEx\\DragNWash.Installer に入れる",
                [Key.PlanLaunchOptionAdd] = "Steam のゲームの起動オプションに、更新用のランチャーを足す（前からある起動オプションはそのまま）",
                [Key.PlanLaunchOptionHave] = "更新用のランチャーは、もう Steam のゲームの起動オプションに入っている",
                [Key.PlanLaunchOptionRemove] = "Steam のゲームの起動オプションから、更新用のランチャーを外す（ほかの起動オプションはそのまま）",
                [Key.PlanRemoveLauncher] = "BepInEx\\DragNWash.Installer から更新用のランチャー（Launcher.exe とそのファイル）を削除する",
                [Key.SteamHead] = "先に Steam を閉じてください",
                [Key.SteamBody] = "Steam が起動しています。起動オプションを設定するには Steam の設定ファイルを書き換えますが、Steam は起動している間このファイルを上書きしてしまいます。",
                [Key.SteamBodyRemove] = "Steam が起動しています。起動オプションを変えるには Steam の設定ファイルを書き換えますが、Steam は起動している間このファイルを上書きしてしまいます。",
                [Key.SteamKeep] = "前からある起動オプションはそのまま残します。",
                [Key.SteamClose] = "Steam を閉じる",
                [Key.SteamSelf] = "自分で閉じる",
                [Key.SteamSkip] = "起動オプションは設定しない",
                [Key.SteamSkipRemove] = "起動オプションはそのままにする",
                [Key.SteamWaiting] = "Steam が閉じるのを待っています... 閉じたら、そのまま続けます。",
                [Key.SteamClosing] = "Steam を閉じています... 閉じたら、そのまま続けます。",
                [Key.SteamSlow] = "{0} 秒たっても Steam が閉じません。Steam を自分で閉じる（Steam メニューの「終了」）か、今回は起動オプションを変えずに続けてください。",
                [Key.DoneLauncher] = "更新用のランチャー：BepInEx\\DragNWash.Installer に入れました",
                [Key.DoneLaunchOptionAdded] = "Steam の起動オプション：更新用のランチャーを足しました（前からあるものはそのまま）",
                [Key.DoneLaunchOptionRemoved] = "Steam の起動オプション：更新用のランチャーを外しました",
                [Key.DoneLaunchOptionSkipped] = "Steam の起動オプション：変えていません",
                [Key.DoneLaunchOptionFailed] = "Steam の起動オプション：変えられませんでした（理由はログにあります）",
                [Key.WebMinimize] = "最小化",
                [Key.WebStateSetup] = "インストーラー",
                [Key.WebStateInstalling] = "インストールしています",
                [Key.WebStateUpdating] = "更新しています",
                [Key.WebStateUninstalling] = "アンインストールしています",
                [Key.WebStateInstalled] = "インストールしました",
                [Key.WebStateUpdated] = "更新しました",
                [Key.WebStateUninstalled] = "アンインストールしました",
                [Key.WebStateFailed] = "うまくいきませんでした",
                [Key.WebStateCantStart] = "始められません",
                [Key.WebLooking] = "ゲームのフォルダーを探しています",
                [Key.WebFoundIt] = "見つかりました",
                [Key.WebNotFoundIt] = "見つかりませんでした",
                [Key.WebHeadInstall] = "{0} を入れます",
                [Key.WebHeadUpdate] = "{0} から {1} に更新します",
                [Key.WebHeadReinstall] = "{0} を入れ直します",
                [Key.WebHeadUninstall] = "{0} を外します",
                [Key.WebLeadInstall] = "フォルダーと右の一覧を見て、よければ「インストール」を押してください。",
                [Key.WebLeadUpdate] = "設定はそのまま引き継ぎます。右の一覧でよければ「更新」を押してください。",
                [Key.WebLeadUninstall] = "残すものを選んで、右の一覧でよければ「アンインストール」を押してください。",
                [Key.WebLeadNotFound] = "先にゲームのフォルダーを選んでください。",
                [Key.WebFound] = "見つかりました",
                [Key.WebLaunchCheck] = "起動時に更新を確認する",
                [Key.WebLaunchSmall] = "Steam の起動オプションを設定します",
                [Key.WebLaunchNoSteam] = "Steam のアカウントが見つからないので、設定できません",
                [Key.WebLaunchNoLauncher] = "このインストールでは更新用のランチャーが入らないので、設定できません",
                [Key.WebUpdateWill] = "更新ですること：",
                [Key.WebOnline] = "ネット",
                [Key.WebNetAsk] = "「ネット」の付いた行だけインターネットにつなぎます。つなぐ前に、もう一度確かめます。",
                [Key.WebNetLines] = "「ネット」の付いた行だけインターネットにつなぎます。",
                [Key.WebNetNone] = "インターネットにはつなぎません。",
                [Key.WebOtherTitle] = "別の Mod ローダーが入っています",
                [Key.WebOtherText] = "別の Mod ローダーが入っています。ローダーは 1 つのゲームフォルダーに 1 つしか入れられないので、このフォルダーにはインストールできません。",
                [Key.WebOtherTextNamed] = "{0} が入っています。ローダーは 1 つのゲームフォルダーに 1 つしか入れられないので、このフォルダーにはインストールできません。",
                [Key.WebOtherFoot] = "別の Mod ローダーが入っているので、インストールできません。",
                [Key.WebSheetStop] = "やめる（何も変えません）",
                [Key.WebStepCheck] = "入っているものを確認",
                [Key.WebStepCheckSmall] = "ModFramework {0}、BepInEx {1}、ほかのローダーなし",
                [Key.WebStepDownload] = "{0} をダウンロード",
                [Key.WebStepFrom] = "{0} から",
                [Key.WebStepHashSmall] = "届いたファイルが壊れていないか見ます",
                [Key.WebStepBackup] = "バックアップ",
                [Key.WebStepPutSmall] = "ほかの Mod には触れません",
                [Key.WebStepLaunchAdd] = "Steam の起動オプションを設定",
                [Key.WebStepLaunchAddSmall] = "更新用のランチャーを足します",
                [Key.WebStepLaunchRemove] = "Steam の起動オプションから外す",
                [Key.WebStepLaunchRemoveSmall] = "ほかの起動オプションはそのまま",
                [Key.WebPhaseCheck] = "確認しています",
                [Key.WebPhaseDownload] = "ダウンロードしています",
                [Key.WebPhaseVerify] = "SHA-256 を確かめています",
                [Key.WebPhaseBackup] = "バックアップを取っています",
                [Key.WebPhasePut] = "入れています",
                [Key.WebPhaseSet] = "設定しています",
                [Key.WebPhaseLaunch] = "Steam の起動オプションを設定しています",
                [Key.WebPhaseDone] = "入れ終わりました",
                [Key.WebPhaseRemove] = "外しています",
                [Key.WebPhaseRemoved] = "外し終わりました",
                [Key.WebPhaseRollback] = "元に戻しています",
                [Key.WebSubGame] = "ゲームのフォルダー：{0}",
                [Key.WebNetNotYet] = "ゲームのフォルダーにはまだ手を付けていないので、キャンセルしても元のままです。",
                [Key.WebNetWriting] = "ここからはゲームのフォルダーを書き換えるので、キャンセルはできません。途中で失敗したら、元に戻します。",
                [Key.WebNetUninstall] = "外し終わるまで少し待ってください。",
                [Key.WebNetStopping] = "ダウンロードを止めています。ゲームのフォルダーは何も変わっていません。",
                [Key.WebWorkInstall] = "{0} {1} を入れています。",
                [Key.WebWorkUpdate] = "{0} を {1} にしています。",
                [Key.WebWorkUninstall] = "{0} を外しています。",
                [Key.WebDoneInstall] = "インストールが終わりました",
                [Key.WebDoneUpdate] = "更新が終わりました",
                [Key.WebDoneUninstall] = "アンインストールしました",
                [Key.WebDoneLead] = "「ゲームを起動」を押せば、すぐに遊べます。",
                [Key.WebDoneLeadUninstall] = "ゲームのフォルダーから取り除きました。",
                [Key.WebDoneList] = "やったこと",
                [Key.WebReady] = "準備ができました",
                [Key.WebReadyLauncher] = "起動すると、先に更新があるか確かめます",
                [Key.WebReadySteam] = "いつもどおり Steam から起動します",
                [Key.WebUninstalledSmall] = "また入れるときは、この Install.exe を起動してください",
                [Key.WebStart] = "ゲームを起動",
                [Key.WebLog] = "ログ",
                [Key.WebPillSame] = "ゲームのフォルダーは元のままです（何も変えていません）",
                [Key.WebPillBack] = "ゲームのフォルダーは元のままです（元に戻しました、{0} ファイル）",
                [Key.WebPillPartly] = "{0} ファイルは元に戻せませんでした",
                [Key.WebDetails] = "詳細",
                [Key.WebCopied] = "コピーしました",
                [Key.WebBack] = "戻る",
            },
            ["zh"] = new Dictionary<Key, string>
            {
                [Key.Title] = "{0} 安装器",
                [Key.GameFolder] = "游戏文件夹",
                [Key.Browse] = "浏览...",
                [Key.NotFound] = "没找到 Drag'n Wash。请选择游戏文件夹（就是有 DragNWash.exe 的那个）。",
                [Key.Running] = "请先关闭游戏。",
                [Key.NoPayload] = "安装器旁边没有模组文件。请先把 zip 整个解压，再运行解压出来的文件夹里的 Install.exe。",
                [Key.BadManifest] = "读不了安装器旁边的 mod-install.json。",
                [Key.BepInExHash] = "下载的 BepInEx 已损坏或被人改动过（SHA-256 对不上）。什么都没有安装。",
                [Key.OtherLoader] = "这个游戏文件夹里已经有另一个模组加载器了。一个游戏文件夹只能装一个加载器，所以什么都没改。",
                [Key.OtherLoaderNamed] = "这个游戏文件夹里已经有另一个模组加载器（{0}）了。一个游戏文件夹只能装一个加载器，所以什么都没改。",
                [Key.RolledBack] = "复制时出错了，所以已经把所有东西恢复原样（{0} 个文件）。",
                [Key.RolledBackPartly] = "复制时出错了，有 {0} 个文件没能恢复。被覆盖的文件备份在 {1}。",
                [Key.Install] = "安装",
                [Key.Update] = "更新",
                [Key.Uninstall] = "卸载",
                [Key.KeepData] = "保留存档历史和模组的工作文件",
                [Key.AlsoBepInEx] = "如果没有别的模组了，把 BepInEx 也删掉",
                [Key.Installed] = "装好了。请从 Steam 启动游戏。",
                [Key.Uninstalled] = "已卸载。",
                [Key.StatusBepInEx] = "BepInEx",
                [Key.StatusMod] = "已安装的版本",
                [Key.Yes] = "已安装",
                [Key.No] = "未安装",
                [Key.Language] = "安装器语言",
                [Key.Website] = "网站",
                [Key.Working] = "处理中...",
                [Key.SteamLaunchHint] = "在游戏里的 Options → Mods 也可以卸载模组。",
                [Key.Action] = "操作",
                [Key.NothingToUninstall] = "（没有需要卸载的东西）",
                [Key.InstallButton] = "安装(&I)",
                [Key.UpdateButton] = "更新(&U)",
                [Key.UninstallButton] = "卸载(&U)",
                [Key.Close] = "关闭(&C)",
                [Key.InstallWill] = "安装会做这些：",
                [Key.UninstallWill] = "卸载会做这些：",
                [Key.SmartScreenHint] = "Install.exe 没有代码签名，所以 Windows SmartScreen 或 Defender 可能会报警告。它只会做上面列出的这些事。",
                [Key.ListAnd] = " 和 ",
                [Key.ListComma] = "、",
                [Key.PlanDownloadBepInEx] = "从 {1}（实际由 {2} 提供）下载 BepInEx {0}，并校验 SHA-256",
                [Key.PlanHaveBepInEx] = "直接用游戏文件夹里已有的 BepInEx",
                [Key.PlanFrameworkAndMod] = "把 Drag'n Wash ModFramework {0} 和 {1} 放进 BepInEx\\plugins（你自己加的文件会留着）",
                [Key.PlanMod] = "把 {0} 放进 BepInEx\\plugins（你自己加的文件会留着）",
                [Key.PlanKeepNewerFramework] = "保留 Drag'n Wash ModFramework {0}，因为它比这个 zip 里的更新",
                [Key.PlanBackup] = "先把要覆盖的文件备份到 BepInEx\\DragNWash.Installer\\backup",
                [Key.PlanSet] = "把“{0}”设成“{1}”（BepInEx\\config\\{2}）",
                [Key.PlanNothingElse] = "除此之外不会下载或改动任何东西。",
                [Key.PlanOtherLoader] = "游戏文件夹里已经有另一个模组加载器，所以什么都不改，直接停下（一个游戏文件夹只能装一个加载器）",
                [Key.PlanOtherLoaderNamed] = "游戏文件夹里已经有另一个模组加载器（{0}），所以什么都不改，直接停下（一个游戏文件夹只能装一个加载器）",
                [Key.PlanRemovePlugin] = "删除 BepInEx\\plugins\\{0}",
                [Key.PlanRemovePluginKeep] = "删除 BepInEx\\plugins\\{0}，但保留 {1}",
                [Key.PlanRemoveConfig] = "删除 BepInEx\\config\\{0}",
                [Key.PlanRemoveInstallerFolder] = "删除安装器在 BepInEx\\DragNWash.Installer 里的备份",
                [Key.PlanRemoveFramework] = "Drag'n Wash ModFramework 也一起删除（没有别的模组在用）",
                [Key.PlanKeepFramework] = "保留 Drag'n Wash ModFramework（还有别的模组在用：{0}）",
                [Key.PlanRemoveSaveHistory] = "删除 BepInEx\\SaveHistory 中的存档历史",
                [Key.PlanRemoveBepInEx] = "删除 BepInEx",
                [Key.PlanRemoveBepInExKeep] = "删除 BepInEx（要保留的数据会继续留在 BepInEx 文件夹里）",
                [Key.PlanKeepBepInEx] = "保留 BepInEx",
                [Key.PlanKeepBepInExUsed] = "保留 BepInEx（还有别的模组或补丁程序在用）",
                [Key.Cancel] = "取消(&C)",
                [Key.Downloading] = "正在从 {1} 下载 {0}",
                [Key.Cancelled] = "已取消。游戏文件夹没有任何改动。",
                [Key.Stopped] = "已停止。",
                [Key.DownloadFailed] = "BepInEx 下载失败。",
                [Key.DownloadFailedHelp] = "请检查一下网络连接，然后再试一次。游戏文件夹没有任何改动。",
                [Key.CannotWrite] = "没法写入游戏文件夹。",
                [Key.CannotWriteHelp] = "里面的文件可能正在被使用，或者是只读的。请关掉游戏和其他正在用这个文件夹的程序，然后再试一次。",
                [Key.BadZip] = "下载下来的文件不是有效的 zip。",
                [Key.BadZipHelp] = "请再试一次。如果一直这样，请复制详情，贴到错误报告里。",
                [Key.SomethingWrong] = "出了点问题。",
                [Key.SomethingWrongHelp] = "请复制详情，到模组网站上提交错误报告。",
                [Key.ShowDetails] = "显示详情",
                [Key.HideDetails] = "隐藏详情",
                [Key.CopyDetails] = "复制详情(&D)",
                [Key.Retry] = "重试(&R)",
                [Key.StatusFramework] = "ModFramework",
                [Key.PlanDownloadFramework] = "从 {1}（实际由 {2} 提供）下载 Drag'n Wash ModFramework {0}，并校验 SHA-256",
                [Key.PlanFrameworkBring] = "把 ModFramework 的 core 和这个模组用到的 {0} 个库更新到 {1}（已经有更新版本的就保留）",
                [Key.PlanFrameworkBringOne] = "把 ModFramework 的 core 和这个模组用到的库更新到 {1}（已经有更新版本的就保留）",
                [Key.PlanFrameworkBringCore] = "把 ModFramework 的 core 更新到 {1}（已经有更新版本的就保留）",
                [Key.PlanFrameworkSatisfied] = "保留 Drag'n Wash ModFramework {0}：这个模组需要的它都有，不用下载",
                [Key.SmartScreenHintFramework] = "Install.exe 没有代码签名，还会从网上下载 ModFramework，所以 Windows SmartScreen 或 Defender 可能会报警告。它只会做上面列出的这些事。",
                [Key.InstallingNow] = "正在安装：",
                [Key.DoneList] = "已完成：",
                [Key.Done] = "完成。",
                [Key.DownloadHint] = "下载的文件校验完之前不会动游戏文件夹，所以现在取消的话，一切都会保持原样。",
                [Key.StepChecked] = "检查了已安装的内容：ModFramework {0}，BepInEx {1}，没有其他加载器",
                [Key.StepDownload] = "从 {1} 下载 {0}",
                [Key.StepDownloading] = "正在下载 {0} / {1}：{2}（{3} KB / {4} KB）",
                [Key.StepHash] = "校验 SHA-256",
                [Key.StepHashBoth] = "校验 SHA-256",
                [Key.StepBackup] = "把要覆盖的文件备份到 BepInEx\\DragNWash.Installer\\backup",
                [Key.StepPutBepInEx] = "把 BepInEx {0} 放进游戏文件夹",
                [Key.StepPutBoth] = "把 ModFramework 和 {0} 放进 BepInEx\\plugins",
                [Key.StepPut] = "把 {0} 放进 BepInEx\\plugins",
                [Key.StepSet] = "把“{0}”设成“{1}”",
                [Key.DoneFramework] = "ModFramework {0}：{1}",
                [Key.DoneChecked] = "（已校验 SHA-256）",
                [Key.DoneKeptSame] = "保留 {0}：版本一样",
                [Key.DoneKeptNewer] = "保留 {0}：比 ModFramework {1} 里的更新",
                [Key.DoneFrameworkSatisfied] = "ModFramework {0}：这个模组需要的都有了，没有下载",
                [Key.DoneKeptFramework] = "保留 ModFramework {0}：已满足这个模组的最低要求",
                [Key.DoneNotInstalled] = "没有安装：{0}（这个模组用不到）",
                [Key.DoneBepInEx] = "BepInEx {0}（已校验 SHA-256）",
                [Key.DoneSetting] = "“{0}”=“{1}”",
                [Key.DoneOtherMods] = "其他模组：BepInEx\\plugins 里的 {0} 个文件夹没动",
                [Key.DoneOtherModsOne] = "其他模组：BepInEx\\plugins 里的 1 个文件夹没动",
                [Key.DoneBackup] = "被覆盖的 {0} 个文件备份在 {1}",
                [Key.DoneBackupOne] = "被覆盖的 1 个文件备份在 {1}",
                [Key.PartPreloader] = "Preloader",
                [Key.ConsentHead] = "安装器要连接网络",
                [Key.ConsentNeedOlder] = "这个模组需要 Drag'n Wash ModFramework {0}，但游戏文件夹里的是 {1}。安装器会从框架在 GitHub 上的发布页下载。",
                [Key.ConsentNeedMissing] = "这个模组需要 Drag'n Wash ModFramework {0}，但游戏文件夹里没有。安装器会从框架在 GitHub 上的发布页下载。",
                [Key.ConsentNeedParts] = "这个模组需要 Drag'n Wash ModFramework {0} 里的一些部分，游戏文件夹里还没有。安装器会从框架在 GitHub 上的发布页下载。",
                [Key.ConsentWhere] = "连到哪里",
                [Key.ConsentWhereText] = "github.com（{0} 的发布页）\r\n{1}（GitHub 存放文件的地方，github.com 会自动把安装器转到这里）",
                [Key.ConsentWhy] = "为什么",
                [Key.ConsentWhyText] = "只为下载一次 {0}。",
                [Key.ConsentSent] = "发送什么",
                [Key.ConsentSentText] = "只有普通的 HTTPS 请求和 User-Agent {0}。不会发送你的名字、文件夹位置、登录信息或 Cookie。不过和访问任何网站一样，GitHub 能看到你的 IP 地址。",
                [Key.ConsentCheck] = "校验",
                [Key.ConsentCheckText] = "只有 SHA-256 和这个模组发布时记下的值一样，才会用它。在那之前，游戏文件夹不会有任何改动。",
                [Key.ConsentCheckTextBoth] = "两个文件都只有在 SHA-256 和这个模组发布时（ModFramework）或安装器里（BepInEx）记下的值一样时，才会用。在那之前，游戏文件夹不会有任何改动。",
                [Key.ConsentNoApi] = "不会连接 api.github.com。如果选你自己下载的 zip，就完全不用联网。",
                [Key.ConsentNoApiBepInEx] = "不会连接 api.github.com。就算选你自己下载的 ModFramework zip，BepInEx 还是要下载。",
                [Key.OpenReleasePage] = "打开发布页",
                [Key.ChooseZip] = "选择 zip(&Z)...",
                [Key.DownloadAndInstall] = "下载并安装(&D)",
                [Key.CancelPlain] = "取消",
                [Key.ChooseZipTitle] = "选择 {0}",
                [Key.NetOffline] = "安装器连不上网。",
                [Key.NetBusy] = "GitHub 没有回应，或者返回了错误。请过几分钟再试。",
                [Key.NetLimited] = "GitHub 现在在限制下载。请 {0} 分钟后再试。",
                [Key.NetLimitedLater] = "GitHub 现在在限制下载。请稍后再试。",
                [Key.NetTls] = "没法确认和 GitHub 之间是安全连接。",
                [Key.FwNotPublished] = "ModFramework {0} 还没有发布。请告诉模组作者。",
                [Key.FwDownloadFailed] = "ModFramework {0} 下载失败。",
                [Key.FwSize] = "下载的 ModFramework {0} 大小和这个模组发布时记下的不一样。",
                [Key.FwHash] = "下载的 ModFramework {0} 和这个模组发布时记下的对不上（SHA-256）。",
                [Key.FwLocalMismatch] = "你选的 zip 不是这个模组发布时记下的 ModFramework {0}（大小或 SHA-256 不一样）。",
                [Key.FwNoDownload] = "需要下载 ModFramework {0}，但下载被关掉了（--no-download）。请用 --framework-zip 指定 zip。",
                [Key.BepInExNoDownload] = "需要下载 BepInEx {0}，但下载被关掉了（--no-download）。请用 --bepinex-zip 指定 zip。",
                [Key.FwZipLacks] = "ModFramework {0} 里没有这个模组要用的 {1}。请告诉模组作者。",
                [Key.FwZipTooOld] = "ModFramework {0} 里的 {1} 是 {2}，但这个模组要 {3} 或更新的版本。请告诉模组作者。",
                [Key.FwKeepNotMet] = "已安装的 ModFramework 达不到这个模组的最低要求，所以要安装 ModFramework {0}。",
                [Key.NothingChanged] = "游戏文件夹没有任何更改。",
                [Key.FwDeletedHelp] = "这个文件没有用上，已经删掉了。游戏文件夹没有任何改动。",
                [Key.FwNotUsedHelp] = "这个 zip 没有用上。游戏文件夹没有任何改动。",
                [Key.FwManualHelp] = "你也可以自己从发布页下载 zip，再用“选择 zip”选中它。它会用同样的方式校验。",
                [Key.FwReleaseLink] = "打开发布页（{0}）",
                [Key.FwKeepLink] = "保留 ModFramework {0}，只安装模组（它已满足这个模组的最低要求）",
                [Key.LaunchOptionCheck] = "游戏启动时检查模组更新（设置 Steam 启动选项）",
                [Key.PlanLauncher] = "把更新用的启动器（Launcher.exe）放进 BepInEx\\DragNWash.Installer",
                [Key.PlanLaunchOptionAdd] = "在 Steam 里这个游戏的启动选项中加上更新用的启动器（原有的启动选项保持不变）",
                [Key.PlanLaunchOptionHave] = "更新用的启动器已经在 Steam 里这个游戏的启动选项中了",
                [Key.PlanLaunchOptionRemove] = "从 Steam 里这个游戏的启动选项中去掉更新用的启动器（其他启动选项保持不变）",
                [Key.PlanRemoveLauncher] = "从 BepInEx\\DragNWash.Installer 删除更新用的启动器（Launcher.exe 和它的文件）",
                [Key.SteamHead] = "请先关闭 Steam",
                [Key.SteamBody] = "Steam 正在运行。设置启动选项要改写 Steam 的一个设置文件，而 Steam 运行时会覆盖这个文件。",
                [Key.SteamBodyRemove] = "Steam 正在运行。更改启动选项要改写 Steam 的一个设置文件，而 Steam 运行时会覆盖这个文件。",
                [Key.SteamKeep] = "原有的启动选项会保留。",
                [Key.SteamClose] = "帮我关闭 Steam",
                [Key.SteamSelf] = "我自己关",
                [Key.SteamSkip] = "不设置启动选项",
                [Key.SteamSkipRemove] = "启动选项保持不变",
                [Key.SteamWaiting] = "正在等 Steam 关闭……关闭后会自动继续。",
                [Key.SteamClosing] = "正在关闭 Steam……关闭后会自动继续。",
                [Key.SteamSlow] = "过了 {0} 秒 Steam 还没有关闭。请自己关闭 Steam（Steam 菜单 →“退出”），或者这次不更改启动选项，直接继续。",
                [Key.DoneLauncher] = "更新用的启动器：已放进 BepInEx\\DragNWash.Installer",
                [Key.DoneLaunchOptionAdded] = "Steam 启动选项：已加上更新用的启动器（原有的保持不变）",
                [Key.DoneLaunchOptionRemoved] = "Steam 启动选项：已去掉更新用的启动器",
                [Key.DoneLaunchOptionSkipped] = "Steam 启动选项：没有更改",
                [Key.DoneLaunchOptionFailed] = "Steam 启动选项：没能更改（原因见日志）",
                [Key.WebMinimize] = "最小化",
                [Key.WebStateSetup] = "安装器",
                [Key.WebStateInstalling] = "正在安装",
                [Key.WebStateUpdating] = "正在更新",
                [Key.WebStateUninstalling] = "正在卸载",
                [Key.WebStateInstalled] = "已安装",
                [Key.WebStateUpdated] = "已更新",
                [Key.WebStateUninstalled] = "已卸载",
                [Key.WebStateFailed] = "没有成功",
                [Key.WebStateCantStart] = "无法开始",
                [Key.WebLooking] = "正在找游戏文件夹",
                [Key.WebFoundIt] = "找到了",
                [Key.WebNotFoundIt] = "没找到",
                [Key.WebHeadInstall] = "安装 {0}",
                [Key.WebHeadUpdate] = "从 {0} 更新到 {1}",
                [Key.WebHeadReinstall] = "重新安装 {0}",
                [Key.WebHeadUninstall] = "卸载 {0}",
                [Key.WebLeadInstall] = "看一下文件夹和右边的列表，没问题就按“安装”。",
                [Key.WebLeadUpdate] = "设置会原样保留。右边的列表没问题就按“更新”。",
                [Key.WebLeadUninstall] = "选好要保留的东西，右边的列表没问题就按“卸载”。",
                [Key.WebLeadNotFound] = "请先选择游戏文件夹。",
                [Key.WebFound] = "找到了",
                [Key.WebLaunchCheck] = "游戏启动时检查模组更新",
                [Key.WebLaunchSmall] = "会设置 Steam 启动选项",
                [Key.WebLaunchNoSteam] = "没找到 Steam 账户，所以没法设置",
                [Key.WebLaunchNoLauncher] = "这次安装不会放入更新用的启动器，所以没法设置",
                [Key.WebUpdateWill] = "更新会做这些：",
                [Key.WebOnline] = "联网",
                [Key.WebNetAsk] = "只有标着“联网”的行会用到网络，联网前还会再问你一次。",
                [Key.WebNetLines] = "只有标着“联网”的行会用到网络。",
                [Key.WebNetNone] = "不会用到网络。",
                [Key.WebOtherTitle] = "这个文件夹里有别的模组加载器",
                [Key.WebOtherText] = "这里已经有另一个模组加载器了。一个游戏文件夹只能装一个加载器，所以没法安装到这个文件夹。",
                [Key.WebOtherTextNamed] = "这里已经有 {0} 了。一个游戏文件夹只能装一个加载器，所以没法安装到这个文件夹。",
                [Key.WebOtherFoot] = "这里有别的模组加载器，所以没法安装。",
                [Key.WebSheetStop] = "不做了（什么都不改）",
                [Key.WebStepCheck] = "检查已安装的内容",
                [Key.WebStepCheckSmall] = "ModFramework：{0}，BepInEx：{1}，没有其他加载器",
                [Key.WebStepDownload] = "下载 {0}",
                [Key.WebStepFrom] = "来自 {0}",
                [Key.WebStepHashSmall] = "确认下载的文件完整无损",
                [Key.WebStepBackup] = "备份",
                [Key.WebStepPutSmall] = "不会动其他模组",
                [Key.WebStepLaunchAdd] = "设置 Steam 启动选项",
                [Key.WebStepLaunchAddSmall] = "加上更新用的启动器",
                [Key.WebStepLaunchRemove] = "从 Steam 启动选项中去掉",
                [Key.WebStepLaunchRemoveSmall] = "其他启动选项保持不变",
                [Key.WebPhaseCheck] = "正在检查",
                [Key.WebPhaseDownload] = "正在下载",
                [Key.WebPhaseVerify] = "正在校验 SHA-256",
                [Key.WebPhaseBackup] = "正在备份",
                [Key.WebPhasePut] = "正在放入文件",
                [Key.WebPhaseSet] = "正在设置",
                [Key.WebPhaseLaunch] = "正在设置 Steam 启动选项",
                [Key.WebPhaseDone] = "都装好了",
                [Key.WebPhaseRemove] = "正在删除",
                [Key.WebPhaseRemoved] = "都删好了",
                [Key.WebPhaseRollback] = "正在恢复原样",
                [Key.WebSubGame] = "游戏文件夹：{0}",
                [Key.WebNetNotYet] = "游戏文件夹还没有动过，所以现在取消的话，一切都会保持原样。",
                [Key.WebNetWriting] = "从这里开始会改动游戏文件夹，所以没法取消了。如果中途出错，会全部恢复原样。",
                [Key.WebNetUninstall] = "马上就好，请稍等。",
                [Key.WebNetStopping] = "正在停止下载。游戏文件夹没有任何改动。",
                [Key.WebWorkInstall] = "正在放入 {0} {1}。",
                [Key.WebWorkUpdate] = "正在把 {0} 更新到 {1}。",
                [Key.WebWorkUninstall] = "正在卸载 {0}。",
                [Key.WebDoneInstall] = "安装好了",
                [Key.WebDoneUpdate] = "更新好了",
                [Key.WebDoneUninstall] = "已卸载",
                [Key.WebDoneLead] = "按“启动游戏”就能马上开玩。",
                [Key.WebDoneLeadUninstall] = "已经从游戏文件夹里删掉了。",
                [Key.WebDoneList] = "做了什么",
                [Key.WebReady] = "可以玩了",
                [Key.WebReadyLauncher] = "启动时会先检查有没有更新",
                [Key.WebReadySteam] = "像平常一样由 Steam 启动",
                [Key.WebUninstalledSmall] = "想重新安装的话，再运行这个 Install.exe 就行",
                [Key.WebStart] = "启动游戏",
                [Key.WebLog] = "日志",
                [Key.WebPillSame] = "游戏文件夹保持原样（什么都没改）",
                [Key.WebPillBack] = "游戏文件夹保持原样（已恢复 {0} 个文件）",
                [Key.WebPillPartly] = "有 {0} 个文件没能恢复",
                [Key.WebDetails] = "详情",
                [Key.WebCopied] = "已复制",
                [Key.WebBack] = "返回",
            },
        };

        internal static readonly string[] Languages = { "en", "ja", "zh" };

        internal static string Current = Detect();

        internal static string Detect()
        {
            string name = CultureInfo.CurrentUICulture.Name;
            if (name.StartsWith("ja")) return "ja";
            if (name.StartsWith("zh")) return "zh";
            return "en";
        }

        internal static string Get(Key key, params object[] args)
        {
            string text = All.TryGetValue(Current, out var table) && table.TryGetValue(key, out string s) ? s : All["en"][key];
            return args.Length == 0 ? text : string.Format(text, args);
        }

        // For bug reports and the log, which stay English whatever the window shows.
        internal static string English(Key key, params object[] args)
        {
            return args.Length == 0 ? All["en"][key] : string.Format(All["en"][key], args);
        }

        // The windows' font for the installer language. Windows' own font for another
        // script draws the missing characters from a fallback font it did not measure
        // them with, so a line that should wrap ran past the right edge instead (Chinese
        // on Japanese Windows). Windows in the language itself keeps its own font.
        internal static Font UiFont()
        {
            Font system = SystemFonts.MessageBoxFont;
            string ui = CultureInfo.CurrentUICulture.Name;
            string family =
                Current == "ja" && !ui.StartsWith("ja") ? "Yu Gothic UI" :
                Current == "zh" && !(ui == "zh-CN" || ui == "zh-SG" || ui.StartsWith("zh-Hans")) ? "Microsoft YaHei UI" :
                null;
            if (family == null)
            {
                return system;
            }
            var font = new Font(family, system.SizeInPoints);
            if (font.Name == family)
            {
                return font;
            }
            // Not installed (Windows 7 has no Yu Gothic UI): Windows' own font as before.
            font.Dispose();
            return system;
        }

        internal static string LanguageName(string code)
        {
            switch (code)
            {
                case "ja": return "日本語";
                case "zh": return "中文";
                default: return "English";
            }
        }
    }
}
